---
- hosts: kubernetes-master
  sudo: true
  tasks:
    - name: Ensure required packages are at latest versions
      apt: pkg={{ item }} state=latest
      with_items:
        - python3-dev
        - python3-pip
        - git
        - build-essential
        - vim
        - dtrx
        - htop
        - docker.io
        - bridge-utils
