---
- hosts: kubernetes-master
  become: yes

  vars:
    kubernetes_master_ip: 127.0.0.1
    flannel_range: 10.130.0.0/16

  tasks:
    - name: Disable involved services
      service: name="{{ item }}" state=stopped
      with_items:
        - kubernetes-service-proxy
        - kubernetes-master
        - docker
        - setup-flannel
        - flannel
        - etcd-waiter
        - etcd
        - bootstrap-docker

    - name: Ensure required packages are at latest versions
      apt: pkg={{ item }} state=latest
      with_items:
        - python3-dev
        - python3-pip
        - git
        - build-essential
        - vim
        - dtrx
        - htop
        - docker.io
        - bridge-utils

    - name: Copy bootstrap docker systemd config
      copy: src=systemd/bootstrap-docker.service
        dest=/etc/systemd/system/bootstrap-docker.service
        owner=root group=root mode=0644

    - name: Copy etcd systemd config
      copy: src=systemd/master/etcd.service
        dest=/etc/systemd/system/etcd.service
        owner=root group=root mode=0644

    - name: Copy etcd waiter
      template: src=scripts/etcd_waiter.sh dest=/usr/local/bin/etcd_waiter.sh
        owner=root group=root mode=0755

    - name: Copy etcd waiter systemd config
      copy: src=systemd/master/etcd-waiter.service
        dest=/etc/systemd/system/etcd-waiter.service
        owner=root group=root mode=0644

    - name: Copy flannel systemd config
      template: src=systemd/master/flannel.service
        dest=/etc/systemd/system/flannel.service
        owner=root group=root mode=0644

    - name: Copy flannel setup script
      copy: src=scripts/setup_flannel.sh dest=/usr/local/bin/setup_flannel.sh
        owner=root group=root mode=0755

    - name: Copy setup-flannel systemd config
      copy: src=systemd/setup-flannel.service
        dest=/etc/systemd/system/setup-flannel.service
        owner=root group=root mode=0644

    - name: Create docker override config dir
      file: path=/etc/systemd/system/docker.service.d/ state=directory

    - name: Copy docker override config
      copy: src=systemd/docker-override.conf
        dest=/etc/systemd/system/docker.service.d/override.conf
        owner=root group=root mode=0644

    - name: Copy kubernetes master systemd config
      template: src=systemd/master/kubernetes-master.service
        dest=/etc/systemd/system/kubernetes-master.service
        owner=root group=root mode=0644

    - name: Copy kubernetes service proxy systemd config
      template: src=systemd/master/kubernetes-service-proxy.service
        dest=/etc/systemd/system/kubernetes-service-proxy.service
        owner=root group=root mode=0644

    - name: Download kubectl
      get_url: url=https://storage.googleapis.com/kubernetes-release/release/v1.0.1/bin/linux/amd64/kubectl
        dest=/usr/local/bin/kubectl mode=0755

    - name: Reload systemd configs
      command: systemctl daemon-reload

    - name: Enable bootstrap docker service
      service: name=bootstrap-docker enabled=yes state=started

    - name: Enable etcd service
      service: name=etcd enabled=yes state=started

    - name: Enable etcd waiter service
      service: name=etcd-waiter enabled=yes state=started

    - name: Enable flannel service
      service: name=flannel enabled=yes state=started

    - name: Enable setup-flannel service
      service: name=setup-flannel enabled=yes state=started

    - name: Enable main docker
      service: name=docker enabled=yes state=started

    - name: Enable kubernetes master service
      service: name=kubernetes-master enabled=yes state=started

    - name: Enable kubernetes service proxy service
      service: name=kubernetes-service-proxy enabled=yes state=started
